configuration:
  DEBUG: true
  APP_NAME: stadocgen
  version: 1.0.0
  about: "Data Standards Documentation Generator"
  description: |
    Python Flask Web Application that generates data standards documentation pages using
    markdown and a set of standardized CSV files.
  scripts:
    "start:dev": main.py
  stack:
    - python
    - flask
    - mermaid.js