configuration:
  DEBUG: true
  APP_NAME: stadocgen
  version: 1.0.0
  about: "Data Standards Documentation Generator"
  description: |
    Python Flask Web Application that generates data standards documentation pages using
    markdown and a set of standardized CSV files.
  stack:
    - python
    - flask
    - mermaid.js
  packages:
    - pandas
    - Flask
    - Flask Frozen
    - pathlib
    - shutil
commands:
  - conda install flask pandas pathlib frozen-flask
