configuration:
  DEBUG: true
  APP_NAME: stadocgen
  version: 1.0.0
  about: "Data Standards Documentation Generator"
  description: |
    Python Flask Web Application that generates data standards documentation pages using
    markdown and a set of standardized CSV files.
  primary stack:
    - python 3.11
    - flask
    - frozen flask
    - pandas
    - jinja
    - mermaid.js
  main packages:
    - pandas: [https://pandas.pydata.org/]
    - Flask: [https://flask.palletsprojects.com/en/3.0.x/]
    - Flask Frozen: [https://frozen-flask.readthedocs.io/en/latest/]
    - pathlib: [https://docs.python.org/3/library/pathlib.html]
    - shutil: [https://docs.python.org/3/library/shutil.html]
    - markup2: [https://github.com/trentm/python-markdown2]
commands:
  - conda install flask pandas pathlib frozen-flask
